# Episodic test prompts for optimizer
# Comment out any prompt you do not want to use.
# This file is auto-updated to add new 0-fidelity prompts, but never removes any.

EPISODIC_TEST_PROMPTS = [
    "intricately carved wooden totem pole",
    "little black chain",
    "sturdy metallic blue pliers",
    "orange glass filled with orange juice above",
    "burgundy pliers insulated handles",
    "dark gray cylindrical body",
    "small white alien with blue eyes",
    "translucent blue-tinted jagged crystal",
    "small metal chisel with green handle",
    "pink drill with metallic shaft",
    "arrow with silver shaft and black head",
    "white fairy with iridescent wings and wand",
    "plastic-handled screwdriver bright orange color",
    "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
    "blue mermaid with scales made",
    "antique ivory curved harp strings",
    "matte gray military military dagger",
    "thick gold bracelet with large square green gemstone in center",
    "metal drill with black handle and blue tip",
    "soldier holding rifle standing",
    "pastel pink silk-draped chaise lounge",
    "mystical purple amulet with symbols",
    "leather-bound ornate crossbow with flintlock",
    "silver necklace with red zircon",
    "golden locket with intricate pattern",
    "futuristic plasma gun with energy core",
    "ornate brass candle holder with flickering flame",
    "small wooden hammer with screws",
    "orange metal pliers with long handles",
    "white bolt with hexagonal shape",
    "gold chain with infinity symbol and cross pendant",
    "pink alien with tentacles on its head",
    "large pink stone on black background",
    "purple heart-shaped keychain on leather strap",
    "small purple alien with large eyes and long tongue",
    "robot that is standing on table",
    "stylish yellow sneakers modern",
    "plastic bucket bright red with white stripes",
    "mythical crystal staff with magical runes",
    "harp with white strings and gold tuning pegs",
    "purple tall robot with single arm",
    "shimmering gold violin with pearl inlay",
    "turquoise necklace with large gemstone",
    "traditional wooden staff adorned with runes",
    "pixie with wand",
    "dark green minivan sliding door wide",
    "thick yellow plastic spoon",
    "toy bear with hat",
    "vintage clarinet in rich dark stain",
    "dark green pickup truck with cargo bed cover",
    "gray robot with two round eyes",
    "small brass candlestick holder with spiral",
    "magical potion bottle with starry label",
    "classic fedora hat in rich brown leather",
    "ruby bracelet with unique twisted band",
    "yellow screwdriver with short handle",
    "yellow and white checkered robot pose",
    "shiny silver spherical robot with smooth finish",
    "glass statue abstract with flowing shapes",
    "glossy gold harp luxurious and enchanting",
    "violet succubus with long",
    "small chisel with black tip",
    "deep navy robot with sophisticated style",
    "glistening yellow citrine prism",
    "large blue crystal with irregular shape and sharp edges",
    "yellow lamp with bent neck",
    "vibrant red vase with elegant swirl",
    "small purple cylindrical creature with short tail and long legs",
    "silver robot wearing green scarf",
    "warm yellow woolen scarf with fringed edges",
    "ruby bracelet adorned with faceted stones",
    "purple suv high roof off-road tires",
    "sapphire mace with gold-plated head",
    "teal camper van rooftop tent and awning",
    "teal suv with",
    "silver pendant necklace featuring infinity symbol",
    "glossy blue clarinet straight body",
    "lustrous black hockey stick slashing",
    "robot in sitting down position",
    "mystical orb pulsating with arcane energy",
    "small winged fairy with golden wings",
    "parachute deployed mid-air high-speed descent",
    "metallic robot turning right",
    "colorful candy in clear glass bottle",
    "black knight armored in shadow",
    "magical lantern casting soft blue glow",
    "purple sapphire in necklace",
    "white pear delicate texture slightly translucent",
    "rose quartz heart pendant symbolizing love",
    "glossy blue glass candle holder elegant",
    "orange electric sander with variable speed",
    "polished steel drums bright and tropical",
    "glimmering orange agate with wavy pattern",
    "heavy-duty green plasma rifle",
    "amethyst anklet with swirling vine-like patterns",
    "copper measuring tape retractable",
    "metal scissors with two sharp blades and curved shape",
    "red triangle with black circle on it",
    "smooth purple lacrosse stick",
    "dark steel knife serrated edge and pointed tip",
    "ornate bronze cannon with curved barrel",
    "red and blue monkey with long tail",
    "silver glowing mermaid",
    "luxurious cream sedan elegant",
    "stone statue ancient warrior in battle pose",
    "jade dragon scale crossbow",
    "blue sharp-edged katana at angle",
    "grey and white pliers",
    "sapphire bracelet adorned with small gleaming stones",
    "clarinet with green covering",
    "heavy-duty gray sledgehammer with leather head",
    "crunchy salted pretzel in bag",
    "transparent crystal with blue color",
    "black and silver pliers",
    "vibrant drum kit red cymbals metallic snares",
    "stud earrings small hoops shiny surface",
    "maroon triangular coaster under cup",
    "purple gun with silencer and metal barrel",
    "platinum earrings capturing fires glow",
    "bronze halberd with twisted iron blade",
    "gold charm bracelet with lock",
    "gray drill with silver bit",
    "classic wood chisel with polished tip",
    "sparkling hexagonal topaz prism",
    "blue pen holder with clips",
    "elegant gold candlestick holder with intricate details",
    "small blue creature with short legs and long nose",
    "platter adorned with sliced turkey breast",
    "glossy black olive within glass bowl",
    "bright orange delivery van with open tailgate",
    "big wooden spoon for stirring",
    "dark green golf club head with yellow shaft",
    "orcs iron helmet with spikes",
    "shiny brass candle holder twin flames",
    "jack in industrial",
    "wooden coffee table with diamond-shaped top",
    "lacrosse stick yellow and black head",
    "translucent blue topaz perched on sleek metal stand",
    "tall slender glass filled with iced lemonade",
    "bright pink minivan with floral pattern",
    "small red plastic screwdriver ergonomic",
    "tiny pink buds on early spring branch",
    "emerald green and gold bangle",
    "knee guards of dark blue",
    "short purple bipedal creature with long neck and small wings",
    "vintage ivory keys piano on stand",
    "onyx hairpin with tiny diamonds",
    "tall ornate wood clarinet",
    "automatic rifle with olive green stock",
    "ornate harp with set of strings and polished",
    "large metal dagger with ivory handle",
    "sapphire cufflinks with silver band",
    "shiny copper robot arm",
    "small spear with emerald",
    "steel drum with multicolored patterns and shiny surface",
    "pixie dancing on bed of stars",
    "small blue donut with chocolate frosting and sprinkles",
    "transparent segmented shell with iridescent edges",
    "green four-legged creature with large ears",
    "green harp standing tall in corner",
    "yellow robot carrying blue toolbox",
    "centaur holding bow standing poised",
    "classic yellow bus with retro",
    "leather-bound black bookshelf tall stature",
    "claymore sword engraved with celtic patterns",
    "large oval-shaped with pointed edges and rough texture blue gem stone",
    "brown wooden shutters set",
    "pink metal wrench with adjustable spanner",
    "delicate harp with curved neck",
    "smokey quartz candlestick holder",
    "glass statue of abstract shape with texture",
    "intricately carved bow in walnut wood",
    "giant marble statue man standing sword raised",
    "ornate gold ring set with sapphire",
    "glass wine glass with stem",
    "obsidian mirror reflecting ethereal shifting landscape",
    "obsidian shard smooth black sheen",
    "single stem of lavender with purple buds",
    "pendant with oval shape and white pearls",
    "tiny green goblin clutching large red gem",
    "scissor jack in garage",
    "purple and long level rod",
    "onyx choker with central drop",
    "spiraling tower made of iridescent rainbow-hued glass",
    "lustrous diamond shard clear and pointed",
    "delicate pearl necklace featuring heart pendant",
    "crunchy salted pretzel in tin",
    "sharp bronze throwing spear",
    "smooth curved cricket bat waiting for impact",
    "slate cherub holding olive branch above head",
    "hockey stick with tape and blade",
    "pale green peridot stone in bronze bowl",
    "octagonal shiny control panel",
    "sleek futuristic pistol with holographic display",
    "purple and pink polka-dotted droid",
    "smooth and round shaped gem",
    "carbon fiber sniper rifle matte black finish scope attached",
    "robot that is energetic and dynamic",
    "white plastic baseball bat standing",
    "staff with glowing runes and mystical powers",
    "shimmering unicorn horn ornament",
    "pearl pendant on silk cord",
    "colorful glass beads in clear glass bottle",
    "green goblin with horns fangs and pointed ears",
    "blue diamond with inclusion",
    "green olive stuffed in cocktail stick",
    "rose quartz hairpin in rose",
    "gray dartboard on stand",
    "heavy-duty steel cricket bat with engraved logo",
    "glossy blue futuristic laser pistol",
    "metal screwdriver bent tip",
    "unique purple sedan with unique wheel designs",
    "emerald bracelet delicate engraved",
    "dark granite statue depicting warrior with spear",
    "small blueberry in basket",
    "rough purple diamond-shaped gem",
    "small green hammer with oval head",
    "large pink irregular shaped stone",
    "terracotta priestess dancing with flowing robes",
    "shiny tourmaline multicolored cylindrical",
    "iridescent opal slice showing rainbow colors in sunlight",
    "moonstone bracelet with silver clasp mechanism",
    "topaz stone golden shine",
    "scissors curved blades sharp",
    "sturdy brown cargo van cargo bay door",
    "intricate ivory mace ornate head",
    "glow-in-the-dark star-shaped pendant on chain",
    "knight shield with lion embossed",
    "frosted turquoise triangular gem",
    "solution crystal clear blue sapphire pendant",
    "wooden clarinet antique look",
    "whimsical windmill turning slowly in breeze",
    "axe with axe head and wooden handle and metal",
    "large green sharp axe",
    "saxophone with gold keys and silver",
    "orange fire truck ladder extended high",
    "banjo with wooden body and strings made of metal wire or nylon string",
    "black toy boat sailed",
    "black metal sturdy shovel",
    "thin brown vase",
    "large smooth amethyst crystal",
    "scissor cutters in white color",
    "large blue drill bit for metal",
    "vintage steel press machine",
    "red sandstone statue of soldier",
    "jade pendant resting on leather cord",
    "vibrant rainbow-colored gelato scoop melting slightly",
    "small plastic basket with yellow handle",
    "burnished bronze spearhead sharp",
    "translucent quartz crystal with clear faceted appearance",
    "elegant clarinet in polished wood",
    "ripe banana hanging by string from ceiling",
    "ivory harp hanging on wall",
    "purple ukulele small guitar-like shape",
    "feathered quiver holding arrows of various",
    "large wooden tennis racket",
    "jeweled scimitar with flowing emerald inlay patterns",
    "green crooked golf club head",
    "metal screwdriver straight shaft",
    "vibrant orange cone-shaped robot",
    "translucent quartz crystal with clear facets",
    "steel drum tropical pattern",
    "bright yellow saxophone with smooth keys",
    "cube-shaped bot in matte-black",
    "white table with three chairs and plant on it",
    "golden harp with delicate filigree detailing",
    "boxing glove with red stripes and white lining",
    "matte blue turquoise fragment",
    "dark green leafy branch",
    "big clear brown stone",
    "tiny robot with round yellow eyes",
    "large square silver bracelet with sapphire in corner",
    "bow with green wood body and white string",
    "multi-colored vibrant agate slice",
    "centaur archer poised bowstring taut aiming skyward",
    "polished rosewood clarinet in sheath",
    "cracked obsidian ancient spearhead",
    "plastic straw of drink",
    "small yellow triangular wooden kitchen knife",
    "ukulele sporting vibrant sunflower yellow",
    "white elf holding ancient golden staff",
    "purple troll with long hair and green",
    "long narrow black drill",
    "modern futuristic assault rifle",
    "velvet green sofa with gold piping",
    "sharp red bayonet on rifle",
    "statue of animal flying on pedestal",
    "banana split with toppings",
    "large shiny silver screwdriver",
    "glass vase with intricate blue patterns",
    "huge pink dinosaur with blue spots",
    "deep green emerald sleek cut",
    "charming pink minivan sporting floral decals",
    "sleek blue cricket bat poised",
    "lime green golf club",
    "eggshell green metal screwdriver with silver handle",
    "robot with red and blue stripes in crate",
    "sturdy plastic bucket bright yellow color useful for painting",
    "whole wheat pizza with extra cheese",
    "green alien with large head and big eyes",
    "green hammer with wood",
    "matte-black octahedral robot with sharp edges",
    "robot with orange star shape",
    "small white square-shaped quartz crystal with gold chain",
    "amethyst teardrop-shaped earrings set in gold",
    "blue polycarbonate drill bit",
    "greek amphora scene detail",
    "necklace with opals in it",
    "harmonica in classic matte black",
    "rose gold locket necklace with floral",
    "robot with olive green circle shape",
    "green sports car sleek aerodynamic",
    "glossy blue saxophone with sleek lines",
    "small and oval shaped black gemstone with rough surface and dark color",
    "green leafy staff with heart-shaped handle",
    "bright orange baseball bat with intricate wood grain",
    "limestone figure of dancing faun",
    "heavy-duty wrench black and yellow stripes",
    "gold-trimmed sword elegant curve",
    "lightweight white chisel with pointed end",
    "radiant heart-shaped opal necklace",
    "large golden trowel",
    "green squash racket streamlined",
    "dull irregular quartz crystal",
    "sturdy metal screwdriver tip pointed blue handle",
    "black clarinet classic and timeless",
    "green rubber gloves pack",
    "sleek green marimba",
    "glowing tower with spiraling silver staircases",
    "matte black bass guitar with sleek modern",
    "blue putty knife flat surface",
    "white ice cube tray",
    "antique silver candlestick two-pronged",
    "old-fashioned hammer with black head",
    "matte blue cricket bat stands ready",
    "drill bit yellow slender pointed tip",
    "onyx helmet crowned by sapphire crest",
    "textured jasper mineral chunk",
    "polished silver clarinet with elegant",
    "golden intricate long crossbow",
    "dark green van reversing now",
    "silver serpent coiled around glowing crystal staff",
    "saxophone mouthpiece in elegant silver",
    "white wooden golf club head",
    "enormous black robot with round body",
    "bow with green handle and yellow bow",
    "wooden flute adorned with colorful beads",
    "glowing staff topped with radiant sapphire stone",
    "sapphire-studded sharp spear",
    "emerald pendant",
    "bottle of red wine with cork in it",
    "crystal staff with swirling light",
    "harp adorned with pearl inlays and gilded frame",
    "necklace with heart-shaped pendant made of silver and turquoise stones",
    "cupcake with chocolate icing on top",
    "matte black candle holder two interlocking pieces",
    "greek kylix cup black-figure technique mythological scenes",
    "small round blue creature with long nose and pointed ears",
    "tall glass of layered lemonade",
    "cylindrical glass of bubbly lemonade",
    "small pink robot with round eyes and metal arms",
    "aquamarine hairpin with spiral form",
    "ivory maiden with lute",
    "white van cargo boxes subarban",
    "green hexagonal torso on robot",
    "organge plastic cup with two handles on either side of cup",
    "yellow robot with shiny metallic surface",
    "pink frosted donus hold on stick",
    "short green creature with long tail and sharp claws",
    "diamond suspended by platinum chain"
]