# Episodic Test Prompts - Cleaned and Deduplicated
# This file contains unique prompts for episodic optimization testing
# Generated automatically - do not edit manually

EPISODIC_TEST_PROMPTS = [
    
    "silver circlet on head",
    "animal-plant hybrid-like object",
    "long narrow yellow spatula tip",
    "a ludovico anticos lute with a smooth, polished wooden body and finely carved, golden rosettes",
    "rose quartz lion figurine",
    "ivory scepter crowned with sparkling opal",
    "coral bead necklace in vibrant colors",
    "an emerald green wool sweater with a snug fit and ribbed cuffs",
    "glowing crystal staff with dragon head handle",
    "blue cybernetic owl perched on branch",
    "bright yellow daisy-like flowers",
    "pink scooter parked away",
    "polished chrome figure of cat with wings",
    "a hammock, made of woven cotton ropes and a sturdy wooden frame, swaying gently in the breeze",
    "a sparkling tinsel christmas tree topper with multicolored strands and a star-shaped finial",
    "metal statue mannequin arm extended",
    "blue velvet love seat two cushions",
    "art deco gold finish tea trolley with wheels",
    "polished ivory-handled revolver with sunburst pattern",
    "an old-fashioned amber glass bottle with a thick, curved body and a slightly chipped label",
    "silver truck with gold trim and tinted windows",
    "red crystal pendant with crescent moon",
    "german shepherd trotting calmly",
    "jeweled amulet emitting faint azure glow",
    "roman candlestick holder tall and slender",
    # "copper wire cutter placed in toolset",
    # "statue of liberty with torch raised",
    # "tiny purple chisel for detailed woodwork",
    # "wise old wizard reading ancient tome",
    # "roman bust of general stern",
    # "brown recliner with padded back",
    # "gemstone-embedded brooch vibrant hues in sunburst pattern",
    # "platinum ring with ruby and diamond setting",
    # "white linen blouse floral print",
    # "silver breastplate with leather lining",
    # "egyptian scarab brooch polished green jade surface",
    # "the three graces by rubens, depicting three beautiful female figures with flowing robes and soft, pastel colors",
    # "matte blue cricket bat stands ready",
    # "drill bit yellow slender pointed tip",
    # "onyx helmet crowned by sapphire crest",
    # "textured jasper mineral chunk",
    # "polished silver clarinet with elegant",
    # "golden intricate long crossbow",
    # "dark green van reversing now",
    # "silver serpent coiled around glowing crystal staff",
    # "saxophone mouthpiece in elegant silver",
    # "white wooden golf club head",
    # "enormous black robot with round body",
    # "bow with green handle and yellow bow",
    # "wooden flute adorned with colorful beads",
    # "glossy blue clarinet straight body",
    # "lustrous black hockey stick slashing",
    # "intricately carved wooden totem pole",
    # "little black chain",
    # "sturdy metallic blue pliers",
    # "orange glass filled with orange juice above",
    # "burgundy pliers insulated handles",
    # "dark gray cylindrical body",
    # "small white alien with blue eyes",
    # "translucent blue-tinted jagged crystal",
    # "small metal chisel with green handle",
    # "pink drill with metallic shaft",
    # "arrow with silver shaft and black head",
    # "white fairy with iridescent wings and wand",
    # "plastic-handled screwdriver bright orange color",
    # "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
    # "blue mermaid with scales made",
    # "antique ivory curved harp strings",
    # "matte gray military military dagger",
    # "thick gold bracelet with large square green gemstone in center",
    # "metal drill with black handle and blue tip",
    # "soldier holding rifle standing",
    # "pastel pink silk-draped chaise lounge",
    # "mystical purple amulet with symbols",
    # "leather-bound ornate crossbow with flintlock",
    # "silver necklace with red zircon",
    # "golden locket with intricate pattern",
    # "futuristic plasma gun with energy core",
    # "ornate brass candle holder with flickering flame",
    # "small wooden hammer with screws",
    # "orange metal pliers with long handles",
    # "white bolt with hexagonal shape",
    # "gold chain with infinity symbol and cross pendant",
    # "pink alien with tentacles on its head",
    # "large pink stone on black background",
    # "mysterious fog-covered cottage with glowing windows",
    # "long blue sci-fi energy sword",
    # "golden bronze statue abstract form",
    # "polished wood statue of horse rearing up",
    # "black dwarf with shiny metal body",
    # "blue-and-yellow large-beaked toucan",
    # "geometric purple necklace",
    # "dark brown cricket bat curved and robust",
    # "baseball glove pocket depth",
    # "textured golf club teed up drive",
    # "interstellar starship with wings",
    # "goblin king wearing jeweled crown",
    # "amethyst bracelet purple hued smooth surface",
    # "curved metal side table glossy black finish",
    # "standing angel statue in white marble",
    # "alabaster idol serene eyes",
    # "sushi platter with was",
    # "chic navy blue jumpsuit",
    # "big metal statue of flower",
    # "twisted vine with spiraling emerald leaves",
    # "tiny triangular silver key chain",
    # "violet-hued pixie with iridescent wings",
    # "eagle soaring above mountain sharp eyesight",
    # "droid body part with wires exposed",
    # "marble statue of queen in regal attire",
    # "ornate jeweled mace with dragon head pomm",
    # "broad leafed plant with white spots",
    # "kraken tentacle with ink-black skin",
    # "clear green gem stone with sparkles",
    # "matte silver measuring cup",
    # "metal statue with blue robe",
    # "emerald-studded ceremonial mace with golden ferrule",
    # "yellow minotaur in combat stance",
    # "tin of sweet caramel candies",
    # "black dwarf wielding iron",
    # "bamboo dining mat woven pattern",
    # "clear plastic drinking glass pitcher",
    # "racing bike with custom",
    # "medieval halberd with iron spike tip",
    # "satin blouse scoop neck sheer sleeves",
    # "elegant chess pieces collection",
    # "purple star-shaped laser blaster gun",
    # "colorful winged staff",
    # "bronze rugged robot in sitting position",
    # "aged bronze rapier in embossed leather scabbard",
    # "streamlined spacecraft with solar sail deployment",
    # "yellow six-limbed creature",
    # "detailed red and blue airplane toy",
    # "enchanted pink mermaid singing in coral cove",
    # "orange bird with feathers on its body",
    # "iridescent holographic hexagonal cube",
    # "orchid bloom atop green mossy rock",
    # "vintage necklace with turquoise stones",
    # "imposing black panther crouching on slab",
    # "trapezoidal red garnet crystal",
    # "armored car with lights",
    # "infantry soldier wearing helmet and flak vest",
    # "a theremin, an electronic musical instrument played without physical contact, features two metal antennas that emit a haunting, ethereal sound when the players hands are near them",
    # "tall regal creature with feathers",
    # "wyvern with blue flames spewing from mouth",
    # "robot wearing purple cape and holding star",
    # "feathery yellow canary in cage",
    # "helicopter with blue side panels",
    # "heavy-duty orange casting pot",
    # "glossy chrome figure of leaping fish",
    # "rough yellow mineral with cubical shape",
    # "curved yellow putty knife",
    # "silver ring with intricate filigree",
    # "extraterrestrial being with crystalline blue skin",
    # "steampunk inventor holding mechanical monocle",
    # "bear with gold collar",
    # "glow-in-the-dark star-shaped nightlight with buttons",
    # "ebony bass guitar with contoured body",
    # "elegant silvered hilt sword",
    # "emerald combat knife with sheath",
    # "white linear-shaped robotic arm",
    # "magical staff adorned with emeralds",
    # "sturdy bronze dodecahedral robot with intricate",
    # "satyr playing flute horns cur",
    # "energy weapon with blue",
    # "mustard yellow woolen scarf",
    # "cloak of shadows that wraps around wearers",
    # "gemstone brooch with lions head",
    # "pastel pink cardigan with lace trim and buttons",
    # "green plant in terracotta pot tall and leafy",
    # "snowboard with colorful graphic on side",
    # "glossy purple quartz cut into octagon",
    # "durable blue tape roll nearly full",
    # "stainless steel folding tape measure",
    # "tiny plant with dark green leaves and purple flower",
    # "saxophone with unique curve",
    # "creamy mashed potatoes in round dish with fork",
    # "minimalist white cube-shaped automaton",
    # "silver angel in prayer position",
    # "sleek faucet in bathroom sink area",
    # "vibrant orange robot showing mechanical joints",
    # "tall cyborg with metallic blue skin",
    # "vivid red flower",
    # "blackberry perched on copper spoon",
    # "banshees ghostly wailing mask",
    # "colossal stone griffin standing vigilant",
    # "intricate sandstone sculpture of cat lounging",
    # "minimalist black necklace with single diamond",
    # "smooth black fan blade",
    # "black matte-finished robot with small head",
    # "vintage violin with ebony finish",
    # "glowing scepter crowned with ruby jewel",
    # "white metal screwdriver bit set",
    # "black sleek panther staring intently",
    # "ivory statue of seated monk",
    # "sleek nightstand with built-in charging ports",
    # "grey stainless steel knife",
    # "heaping plate of spaghetti bolognese topped with parmesan cheese",
    # "rustic pine bed frame with carved posts",
    # "musket decorated with tribal patterns and feathers",
    # "lily standing in grassy area",
    # "dimpled green robot torso",
    # "silver armor set for warriors",
    # "futuristic humanoid robot standing on single leg",
    # "fiberglass statue of horse running fast",
    # "tall white and slender robot",
    # "crimson drake with intricate patterns",
    # "yellow metal lampstand",
    # "velvet chaise lounge floral patterned throw",
    # "retro green van with wooden interior panels",
    # "carved phoenix in flight",
    # "luminous clear sapphire perched atop glass stand",
    # "satyr with white fur and hooves",
    # "brown cat",
    # "garnet red teardrop-shaped citrine",
    # "streamlined spaceship featuring holographic display",
    # "brass candleholder on mantelp",
    # "green leafed faerie staff",
    # "caramel latte with perfect foam art",
    # "greek vase painted with black figures",
    # "stone-etched armor with leafy pattern",
    # "orange delivery van with graphic advertising wrap",
    # "squat multi-colored daisy in full bloom",
    # "vinyl toy fish swimming deep",
    # "white star-shaped level for precise alignment",
    # "black metal toy drum set",
    # "ancient magical staff",
    # "ball with irregular shape",
    # "gray golem with stone hands",
    # "rugged stone troll menacing with club",
    # "scale armor in gold",
    # "glass vase with green leaf",
    # "a sleek, blue sedan with a smooth, glossy finish and a prominent rear spoiler",
    # "broad flat leaves with ripples",
    # "a delicate ivory carving depicting a serene landscape, with smooth curves and fine details",
    # "a savory dish of vegetables and herbs baked in a seasoned tomato sauce, topped with cheese and breadcrumbs",
    # "a-line dress with spaghetti straps",
    # "abstract dress shirt",
    # "abstract form with sharp edges",
    # "acrylic statue of entity with claws",
    # "alien creature with elongated tail",
    # "alien with organic appearance",
    # "alien-like metallic robot",
    # "almond jar of honey",
    # "amethyst anklet with swirling vine-like patterns",
    # "amethyst necklace complementing velvet dress",
    # "amethyst teardrop-shaped earrings set in gold",
    # "angular blue bot with gold hands",
    # "animal that has mane around its neck",
    # "animal with long neck and feathers",
    # "antique ivory curved harp strings",
    # "antique silver candlestick two-pronged",
    # "apple red scarf",
    # "aquamarine hairpin with spiral form",
    # "arrow with silver shaft and black head",
    # "articulated spider leg joint",
    # "automatic rifle with olive green stock",
    # "axe with axe head and wooden handle and metal",
    # "banana split with toppings",
    # "banjo with wooden body and strings made of metal wire or nylon string",
    # "beast with glowing mane",
    # "beautiful elf with crown",
    # "big clear brown stone",
    # "big wooden spoon for stirring",
    # "black and silver pliers",
    # "black clarinet classic and timeless",
    # "black crystal with facets",
    # "black jiu-jitsu gi folded neatly",
    # "black knight armored in shadow",
    # "black leather apron smooth and durable",
    # "black metal statue of knight riding horse",
    # "black metal sturdy shovel",
    # "black onyx ring looks mysterious",
    # "black toy boat sailed",
    # "blue diamond with inclusion",
    # "blue mermaid with scales made",
    # "blue pen holder with clips",
    # "blue polycarbonate drill bit",
    # "blue putty knife flat surface",
    # "blue sharp-edged katana at angle",
    # "blue spiral-shaped robot crawling on ground",
    # "blue winged fairy holding golden wand",
    # "bomb disposal suit sealed tight",
    # "bottle of red wine with cork in it",
    # "bow with green handle and yellow bow",
    # "bow with green wood body and white string",
    # "boxing glove with red stripes and white lining",
    # "bracelet made of silver with two rubies on top",
    # "bright orange baseball bat with intricate wood grain",
    # "bright orange delivery van with open tailgate",
    # "bright pink minivan with floral pattern",
    # "bright red battery cover",
    # "bright yellow fire truck",
    # "bright yellow lemon cut by metal knife",
    # "bright yellow saxophone with smooth keys",
    # "bronze halberd with twisted iron blade",
    # "brooch of sapphire stars",
    # "brooch with diamond clasp",
    # "brown banshee with long hair flying",
    # "brown chisel sharp-edged and sturdy",
    # "brown horned minotaur charging",
    # "brown leafy robot antenna",
    # "brown marble bathroom vanity top",
    # "brown ottoman under shelf",
    # "brown wooden shutters set",
    # "burgundy pliers insulated handles",
    # "burnished bronze spearhead sharp",
    # "candy cane in glass",
    # "capsule with red emergency hatch",
    # "carbon fiber sniper rifle matte black finish scope attached",
    # "cashmere yellow cardigan crew neck",
    # "centaur archer poised bowstring taut aiming skyward",
    # "centaur holding bow standing poised",
    # "ceramic dollhouse miniature of quaint victorian tea set",
    # "charming pink minivan sporting floral decals",
    # "chic black pantsuit with fitted silhouette",
    # "chic orange scarf warm winter accessory",
    # "chrysanthemum bloom with spots",
    # "clarinet with green covering",
    # "classic fedora hat in rich brown leather",
    # "classic wood chisel with polished tip",
    # "classic yellow bus with retro",
    # "claymore sword engraved with celtic patterns",
    # "clear diamond prism shining on polished silver tray",
    # "cloaked figure holding lantern of light",
    # "clutch in durable construction",
    # "colorful candy in clear glass bottle",
    # "colorful glass beads in clear glass bottle",
    # "compact blue flak jacket",
    # "complex blue motor casing",
    # "copper measuring tape retractable",
    # "cotton tank top with tie-dye effect and scoop neckline",
    # "cracked obsidian ancient spearhead",
    # "creamy white pasta dish with side of marinara sauce",
    # "creature with gold armor and shields",
    # "crimson wyvern claw glove",
    # "crunchy salted pretzel in bag",
    # "crunchy salted pretzel in tin",
    # "crystal spire topped with ruby crown",
    # "crystal staff with swirling light",
    # "crystal-embellished rose-gold hairpin sparkling under light",
    # "crystal-encrusted brooch catching every ray",
    # "crystalline star-shaped silver fluorite",
    # "cube-shaped bot in matte-black",
    # "cupcake with chocolate icing on top",
    # "curved yellow sword",
    # "cutter blade sharp and ready",
    # "cutting torch mounted on cart",
    # "cylindrical glass of bubbly lemonade",
    # "dainty gold chain holding single pearl",
    # "dappled gray elf wearing intricate cloak",
    # "dark blue robot with oval body",
    # "dark blue woolen tunic",
    # "dark faceted black diamond",
    # "dark glossy black piano keys",
    # "dark granite statue depicting warrior with spear",
    # "dark gray cylindrical body",
    # "dark gray minimalist robot",
    # "dark green emerald pointed and faceted",
    # "dark green golf club head with yellow shaft",
    # "dark green leafy branch",
    # "dark green minivan sliding door wide",
    # "dark green pickup truck with cargo bed cover",
    # "dark green van reversing now",
    # "dark steel knife serrated edge and pointed tip",
    # "deep green emerald sleek cut",
    # "deep navy robot with sophisticated style",
    # "deep purple fae staff",
    # "delicate harp with curved neck",
    # "delicate pearl necklace featuring heart pendant",
    # "diamond bracelet heart pattern",
    # "diamond suspended by platinum chain",
    # "diamond-embedded spear with gold shaft",
    # "dinosaur model with yellow spikes",
    # "drill bit yellow slender pointed tip",
    # "dull green cargo train",
    # "dull irregular quartz crystal",
    # "eggshell green metal screwdriver with silver handle",
    # "elegant clarinet in polished wood",
    # "elegant gold candlestick holder with intricate details",
    # "elven princess in long flowing white dress",
    # "emerald bracelet delicate engraved",
    # "emerald green and gold bangle",
    # "emerald necklace pointed tips",
    # "emerald pendant",
    # "enchanted mirror reflecting shadowy ethereal landscape",
    # "enormous black robot with round body",
    # "example prompt (commented out)",
    # "fabric tote bag with multiple pockets and zippers",
    # "fairy with delicate wings and bright smile",
    # "fairys ethereal wings",
    # "fashionable purple handbag crafted from high-quality leather",
    # "feathered quiver holding arrows of various",
    # "formidable black panther crouched on shadowy rock shelf",
    # "frosted turquoise triangular gem",
    # "futuristic plasma gun with energy core",
    # "gentle unicorn with silver horn standing gracefully",
    # "giant marble statue man standing sword raised",
    # "giant white creature with long neck and sharp claws",
    # "glass bowl with rainbow swirl pattern",
    # "glass statue abstract with flowing shapes",
    # "glass statue of abstract shape with texture",
    # "glass vase with intricate blue patterns",
    # "glass wine glass with stem",
    # "gleaming silver clarinet minimalist shape",
    # "glimmering orange agate with wavy pattern",
    # "glistening yellow citrine prism",
    # "glossy black olive within glass bowl",
    # "glossy blue clarinet straight body",
    # "glossy blue futuristic laser pistol",
    # "glossy blue glass candle holder elegant",
    # "glossy blue saxophone with sleek lines",
    # "glossy dark berry clusters",
    # "glossy gold harp luxurious and enchanting",
    # "glow-in-the-dark star-shaped pendant on chain",
    # "glowing iridescent disc in star pattern",
    # "glowing staff topped with radiant sapphire stone",
    # "glowing tower with spiraling silver staircases",
    # "gold chain with infinity symbol and cross pendant",
    # "gold charm bracelet with lock",
    # "gold nunchaku balanced and detailed",
    # "gold-trimmed sword elegant curve",
    # "golden harp with delicate filigree detailing",
    # "golden intricate long crossbow",
    # "golden locket with intricate pattern",
    # "golden trumpet with glossy reflective finish",
    # "grand palace with ornate gilded balconies",
    # "gray dartboard on stand",
    # "gray drill with silver bit",
    # "gray robot with two round eyes",
    # "greek amphora scene detail",
    # "greek kylix cup black-figure technique mythological scenes",
    # "green alien with large head and big eyes",
    # "green crooked golf club head",
    # "green four-legged creature with large ears",
    # "green goblin with horns fangs and pointed ears",
    # "green hammer with wood",
    # "green harp standing tall in corner",
    # "green hexagonal torso on robot",
    # "green leafy staff with heart-shaped handle",
    # "green olive stuffed in cocktail stick",
    # "green rubber gloves pack",
    # "green sports car sleek aerodynamic",
    # "green squash racket streamlined",
    # "grey and white pliers",
    # "harmonica in classic matte black",
    # "harp adorned with pearl inlays and gilded frame",
    # "harp with white strings and gold tuning pegs",
    # "heavy-duty gray sledgehammer with leather head",
    # "heavy-duty green plasma rifle",
    # "heavy-duty steel cricket bat with engraved logo",
    # "heavy-duty wrench black and yellow stripes",
    # "hockey stick with tape and blade",
    # "huge pink dinosaur with blue spots",
    # "intricate gold plate armor set",
    # "intricate ivory mace ornate head",
    # "intricately carved bow in walnut wood",
    # "intricately carved wooden totem pole",
    # "iridescent armor for camouflage purposes",
    # "iridescent opal slice showing rainbow colors in sunlight",
    # "iron trowel with handle",
    # "ivory harp hanging on wall",
    # "ivory maiden with lute",
    # "ivory sofa with armrests and back support",
    # "ivory statue of adult with hands on hips",
    # "jack in industrial",
    # "jade dragon scale crossbow",
    # "jade pendant resting on leather cord",
    # "jeweled scimitar with flowing emerald inlay patterns",
    # "knee guards of dark blue",
    # "knight shield with lion embossed",
    # "lacrosse stick yellow and black head",
    # "large black horse with strong hooves and flowing mane",
    # "large blue crystal with irregular shape and sharp edges",
    # "large blue drill bit for metal",
    # "large exhaust fan with blades",
    # "large golden trowel",
    # "large green sharp axe",
    # "large metal dagger with ivory handle",
    # "large oval-shaped with pointed edges and rough texture blue gem stone",
    # "large pink irregular shaped stone",
    # "large pink stone on black background",
    # "large shiny silver screwdriver",
    # "large smooth amethyst crystal",
    # "large square silver bracelet with sapphire in corner",
    # "large wooden tennis racket",
    # "leather tote bag with handles",
    # "leather-bound black bookshelf tall stature",
    # "leather-bound ornate crossbow with flintlock",
    # "lightweight white chisel with pointed end",
    # "lime green golf club",
    # "lime green ski jacket hood",
    # "limestone figure of dancing faun",
    # "little black chain",
    # "long ears of deer",
    # "long narrow black drill",
    # "luminous pink topaz cabochon",
    # "lustrous black hockey stick slashing",
    # "lustrous diamond shard clear and pointed",
    # "luxurious cream sedan elegant",
    # "magical lantern casting soft blue glow",
    # "magical potion bottle with starry label",
    # "maroon triangular coaster under cup",
    # "matte black bass guitar with sleek modern",
    # "matte black candle holder two interlocking pieces",
    # "matte blue cricket bat stands ready",
    # "matte blue turquoise fragment",
    # "matte gray military military dagger",
    # "matte-black octahedral robot with sharp edges",
    # "medieval halberd with iron-tipped blade",
    # "medium-sized pink aluminum spatula",
    # "mermaid with iridescent tail curled around coral",
    # "metal drill with black handle and blue tip",
    # "metal scissors with two sharp blades and curved shape",
    # "metal screwdriver bent tip",
    # "metal screwdriver straight shaft",
    # "metallic blue robot arm industrial red conveyor silver",
    # "metallic robot turning right",
    # "minotaur wielding club emerging from darkness",
    # "mixer blade in rapid rotation",
    # "modern futuristic assault rifle",
    # "modern glass coffee table near wall",
    # "moonstone bracelet with silver clasp mechanism",
    # "motorized cart at workbench",
    # "multi-colored vibrant agate slice",
    # "multi-hued amethyst teardrop-shaped in crystal bowl",
    # "mystical orb pulsating with arcane energy",
    # "mystical purple amulet with symbols",
    # "mystical sphinx with lion body and eagle wings",
    # "mythical crystal staff with magical runes",
    # "navy blue windbreaker hooded zippered pockets",
    # "necklace with heart-shaped pendant made of silver and turquoise stones",
    # "necklace with opals in it",
    # "obsidian mirror reflecting ethereal shifting landscape",
    # "obsidian shard smooth black sheen",
    # "ochre unicorn with wings spread wide",
    # "octagonal shiny control panel",
    # "old spear with chipped tip",
    # "old-fashioned hammer with black head",
    # "olive green cricket bat worn edges",
    # "onyx choker with central drop",
    # "onyx hairpin with tiny diamonds",
    # "onyx helmet crowned by sapphire crest",
    # "opal anklet featuring wave motifs",
    # "orange electric sander with variable speed",
    # "orange fiberglass handle pliers",
    # "orange fire truck ladder extended high",
    # "orange fitted silk tunic",
    # "orange gemstone with olive green background and orange border",
    # "orange glass filled with orange juice above",
    # "orange metal pliers with long handles",
    # "orange triangular note tray",
    # "orchid with elongated petals in pink",
    # "orcs iron helmet with spikes",
    # "organge plastic cup with two handles on either side of cup",
    # "ornate brass candle holder with flickering flame",
    # "ornate bronze cannon with curved barrel",
    # "ornate gold ring set with sapphire",
    # "ornate harp with set of strings and polished",
    # "ornate staff with golden details",
    # "ornate wand carved from dark oak wood",
    # "oversized pearl necklace with intricate clasp",
    # "painted clay goddess serene with flowers",
    # "pale green peridot stone in bronze bowl",
    # "parachute deployed mid-air high-speed descent",
    # "pastel pink silk-draped chaise lounge",
    # "pearl pendant on silk cord",
    # "pendant with oval shape and white pearls",
    # "pewter statue of angels wings spread wide",
    # "pink alien with tentacles on its head",
    # "pink drill with metallic shaft",
    # "pink frosted donus hold on stick",
    # "pink griffin with golden wings",
    # "pink metal wrench with adjustable spanner",
    # "pinstripe blazer showcasing sharp lapels",
    # "pixie dancing on bed of stars",
    # "pixie with wand",
    # "plastic bucket bright red with white stripes",
    # "plastic colorful toy shovel sitting on shelf",
    # "plastic straw of drink",
    # "plastic-handled screwdriver bright orange color",
    # "plate surrounded by juicy grilled vegetables",
    # "platinum earrings capturing fires glow",
    # "platter adorned with sliced turkey breast",
    # "polished brass crossbow bolt nock",
    # "polished rosewood clarinet in sheath",
    # "polished silver clarinet with elegant",
    # "polished steel drums bright and tropical",
    # "purple and long level rod",
    # "purple and pink polka-dotted droid",
    # "purple cone with patterns",
    # "purple gun with silencer and metal barrel",
    # "purple heart-shaped fairy figurine",
    # "purple heart-shaped keychain on leather strap",
    # "purple rubber jump rope handle",
    # "purple sapphire in necklace",
    # "purple suv high roof off-road tires",
    # "purple tall robot with single arm",
    # "purple troll with long hair and green",
    # "purple ukulele small guitar-like shape",
    # "radiant heart-shaped opal necklace",
    # "rectangular metal shelf with adjustable brackets",
    # "red and blue monkey with long tail",
    # "red sandstone statue of soldier",
    # "red triangle with black circle on it",
    # "ripe banana hanging by string from ceiling",
    # "robot in chefs hat cooking pasta",
    # "robot in sitting down position",
    # "robot that is energetic and dynamic",
    # "robot that is standing on table",
    # "robot with green and purple scarf",
    # "robot with olive green circle shape",
    # "robot with orange star shape",
    # "robot with red and blue stripes in crate",
    # "robotic arm holding bright orange tool",
    # "roller with red rim",
    # "roman glass vase translucent delicate swirls",
    # "rose gold locket necklace with floral",
    # "rose gold metal letter opener on desk",
    # "rose quartz hairpin in rose",
    # "rose quartz heart pendant symbolizing love",
    # "rose quartz vase with smooth curves",
    # "rose-pink tourmaline elongated and shiny",
    # "rough purple diamond-shaped gem",
    # "rough red gemstone with inclusions of minerals",
    # "ruby bracelet adorned with faceted stones",
    # "ruby bracelet with unique twisted band",
    # "sapphire bracelet adorned with small gleaming stones",
    # "sapphire cufflinks with silver band",
    # "sapphire mace with gold-plated head",
    # "sapphire mermaid ear piece",
    # "sapphire shard blue iridesc",
    # "sapphire-studded sharp spear",
    # "saxophone mouthpiece in elegant silver",
    # "saxophone with gold keys and silver",
    # "scissor cutters in white color",
    # "scissor jack in garage",
    # "scissors curved blades sharp",
    # "sharp bronze throwing spear",
    # "sharp red bayonet on rifle",
    # "shimmering gold violin with pearl inlay",
    # "shimmering unicorn horn ornament",
    # "shiny brass candle holder twin flames",
    # "shiny brass cymbals with sharp",
    # "shiny copper robot arm",
    # "shiny rifle stock finish",
    # "shiny silver spherical robot with smooth finish",
    # "shiny sword with fire coming out of blade",
    # "shiny tourmaline multicolored cylindrical",
    # "short blue pitcher",
    # "short green creature with long tail and sharp claws",
    # "short purple bipedal creature with long neck and small wings",
    # "short silver robot antenna",
    # "silver fox figurine trinket",
    # "silver glowing mermaid",
    # "silver necklace with red zircon",
    # "silver pendant necklace featuring infinity symbol",
    # "silver robot wearing green scarf",
    # "silver serpent coiled around glowing crystal staff",
    # "single stem of lavender with purple buds",
    # "slate cherub holding olive branch above head",
    # "sleek black glass coffee table top",
    # "sleek black vase with curved neck on polished wood table",
    # "sleek blue cricket bat poised",
    # "sleek futuristic pistol with holographic display",
    # "sleek green marimba",
    # "sleek katana featuring reflective blade",
    # "small and oval shaped black gemstone with rough surface and dark color",
    # "small blue creature with short legs and long nose",
    # "small blue donut with chocolate frosting and sprinkles",
    # "small blueberry in basket",
    # "small brass candlestick holder with spiral",
    # "small brown garnet with hole in it",
    # "small chisel with black tip",
    # "small green hammer with oval head",
    # "small kitchen chair with wheels",
    # "small metal chisel with green handle",
    # "small pink robot with round eyes and metal arms",
    # "small plastic basket with yellow handle",
    # "small purple alien with large eyes and long tongue",
    # "small purple cylindrical creature with short tail and long legs",
    # "small red plastic screwdriver ergonomic",
    # "small round blue creature with long nose and pointed ears",
    # "small spear with emerald",
    # "small white alien with blue eyes",
    # "small white square-shaped quartz crystal with gold chain",
    # "small winged fairy with golden wings",
    # "small wooden hammer with screws",
    # "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
    # "small yellow triangular wooden kitchen knife",
    # "smokey quartz candlestick holder",
    # "smooth and round shaped gem",
    # "smooth curved cricket bat waiting for impact",
    # "smooth purple lacrosse stick",
    # "soldier holding rifle standing",
    # "soldier in urban camouflage peeking out from building corner",
    # "solution crystal clear blue sapphire pendant",
    # "somber sphinx enigmatic smile",
    # "sparkling hexagonal topaz prism",
    # "spiral glass tower with rainbow reflections",
    # "spiraling tower made of iridescent rainbow-hued glass",
    # "staff with glowing runes and mystical powers",
    # "statue of animal flying on pedestal",
    # "statue wearing long black gown",
    # "stealthy black ninja-robot with hidden blades",
    # "steel drum tropical pattern",
    # "steel drum with multicolored patterns and shiny surface",
    # "stone sculpture of reclining figure hands folded",
    # "stone statue ancient warrior in battle pose",
    # "stud earrings small hoops shiny surface",
    # "sturdy black bus",
    # "sturdy brick trowel flat and wide",
    # "sturdy brown cargo van cargo bay door",
    # "sturdy dark brown drum kit",
    # "sturdy metal screwdriver tip pointed blue handle",
    # "sturdy metallic blue pliers",
    # "sturdy plastic bucket bright yellow color useful for painting",
    # "stylish navy denim overalls adjustable straps",
    # "stylish yellow sneakers modern",
    # "tall glass of layered lemonade",
    # "tall ornate wood clarinet",
    # "tall slender glass filled with iced lemonade",
    # "teal armchair beside beige ottoman",
    # "teal camper van rooftop tent and awning",
    # "teal screwdriver head phillips head size",
    # "teal suv with",
    # "terracotta priestess dancing with flowing robes",
    # "textured jasper mineral chunk",
    # "thick gold bracelet with large square green gemstone in center",
    # "thick yellow plastic spoon",
    # "thin brown vase",
    # "tiny green goblin clutching large red gem",
    # "tiny pink buds on early spring branch",
    # "tiny robot with round yellow eyes",
    # "topaz set in bronze pendant",
    # "topaz stone golden shine",
    # "toy bear with hat",
    # "traditional javelin with feathered shaft",
    # "traditional wooden staff adorned with runes",
    # "translucent acrylic dolphin leap",
    # "translucent blue glass bowl smooth interior walls",
    # "translucent blue topaz perched on sleek metal stand",
    # "translucent blue-tinted jagged crystal",
    # "translucent quartz crystal with clear faceted appearance",
    # "translucent quartz crystal with clear facets",
    # "transparent crystal with blue color",
    # "transparent segmented shell with iridescent edges",
    # "turquoise necklace with large gemstone",
    # "ukulele sporting vibrant sunflower yellow",
    # "ultramarine blue weapon",
    # "unique orange bag bucket shape",
    # "unique purple sedan with unique wheel designs",
    # "veined milky-white agate slab",
    # "velvet green sofa with gold piping",
    # "vibrant blue robot towering and muscular",
    # "vibrant drum kit red cymbals metallic snares",
    # "vibrant emerald crystal cut into perfect hexagon",
    # "vibrant orange cone-shaped robot",
    # "vibrant purple griffin perched atop jagged peak",
    # "vibrant rainbow-colored gelato scoop melting slightly",
    # "vibrant red and gold phoenix figure",
    # "vibrant red garnet in glass case",
    # "vibrant red vase with elegant swirl",
    # "vintage bronze drum kit set",
    # "vintage clarinet in rich dark stain",
    # "vintage ivory keys piano on stand",
    # "vintage lace dress with pearl embellishments",
    # "vintage steel press machine",
    # "viola with blue case",
    # "violet chair with ochre cushion",
    # "violet fantasy wand with crystal tip",
    # "violet succubus with long",
    # "violet tentacled abomination crawling",
    # "warm yellow woolen scarf with fringed edges",
    # "weapon with intricate pattern and wooden handle",
    # "whimsical windmill turning slowly in breeze",
    # "white and red checkerboard chess pieces",
    # "white bolt with hexagonal shape",
    # "white dress with blue bow on back",
    # "white elf holding ancient golden staff",
    # "white fairy with iridescent wings and wand",
    # "white ice cube tray",
    # "white knife and vegetables",
    # "white lamp with book on table and apple",
    # "white lily with glossy green leaves",
    # "white minibus rounded edges",
    # "white pear delicate texture slightly translucent",
    # "white pearl bracelet smooth texture",
    # "white plastic baseball bat standing",
    # "white stone kneeling priestess",
    # "white table with three chairs and plant on it",
    # "white van cargo boxes subarban",
    # "white wooden golf club head",
    # "whole wheat pizza with extra cheese",
    # "wide open petal spread",
    # "winged humanoid with violet skin and long ears",
    # "wingless goblin with staff",
    # "wooden clarinet antique look",
    # "wooden coffee table with diamond-shaped top",
    # "wooden cricket bat polished and glossy",
    # "wooden flute adorned with colorful beads",
    # "wooden robot finger pointing up",
    # "wooden square-shaped saw with metal teeth",
    # "wooden statue of wise old man",
    # "worn-out brown scimitar",
    # "woven cloak of shimmering silk",
    # "xylophone with ivory and silver color",
    # "yellow and white checkered robot pose",
    # "yellow brush in drawer",
    # "yellow crane with swinging hook",
    # "yellow gun with gold engravings on barrel",
    # "yellow lamp with bent neck",
    # "yellow medium-sized robot kneeling",
    # "yellow robot carrying blue toolbox",
    # "yellow robot with shiny metallic surface",
    # "yellow screwdriver with short handle",
    # "yellow wizard with long beard"
]


# Episodic test prompts for optimizer
# Comment out any prompt you do not want to use.
# This file is auto-updated to add new 0-fidelity prompts, but never removes any.


# EPISODIC_TEST_PROMPTS = [
#     "yellow wizard with long beard",
#     "ultramarine blue weapon",
#     "alien creature with elongated tail",
#     "purple cone with patterns",
#     "glossy dark berry clusters",
#     "vibrant purple griffin perched atop jagged peak",
#     "minotaur wielding club emerging from darkness",
#     "lime green ski jacket hood",
#     "wingless goblin with staff",
#     "white lily with glossy green leaves",
#     "mixer blade in rapid rotation",
#     "robot with green and purple scarf",
#     "emerald necklace pointed tips",
#     "white pearl bracelet smooth texture",
#     "animal with long neck and feathers",
#     "yellow crane with swinging hook",
#     "acrylic statue of entity with claws",
#     "violet tentacled abomination crawling",
#     "black crystal with facets",
#     "vintage lace dress with pearl embellishments",
#     "glowing iridescent disc in star pattern",
#     "fairys ethereal wings",
#     "medieval halberd with iron-tipped blade",
#     "viola with blue case",
#     "diamond-embedded spear with gold shaft",
#     "somber sphinx enigmatic smile",
#     "rose quartz vase with smooth curves",
#     "shiny sword with fire coming out of blade",
#     "plastic colorful toy shovel sitting on shelf",
#     "ochre unicorn with wings spread wide",
#     "woven cloak of shimmering silk",
#     "silver fox figurine trinket",
#     "almond jar of honey",
#     "sleek black glass coffee table top",
#     "rectangular metal shelf with adjustable brackets",
#     "alien with organic appearance",
#     "large black horse with strong hooves and flowing mane",
#     "small kitchen chair with wheels",
#     "brown leafy robot antenna",
#     "glass bowl with rainbow swirl pattern",
#     "intricate gold plate armor set",
#     "multi-hued amethyst teardrop-shaped in crystal bowl",
#     "articulated spider leg joint",
#     "a delicate ivory carving depicting a serene landscape, with smooth curves and fine details",
#     "a-line dress with spaghetti straps",
#     "shiny brass cymbals with sharp",
#     "orange gemstone with olive green background and orange border",
#     "veined milky-white agate slab",
#     "ivory statue of adult with hands on hips",
#     "sapphire mermaid ear piece",
#     "cutter blade sharp and ready",
#     "orange fitted silk tunic",
#     "ornate staff with golden details",
#     "brown chisel sharp-edged and sturdy",
#     "sturdy black bus",
#     "purple rubber jump rope handle",
#     "plate surrounded by juicy grilled vegetables",
#     "enchanted mirror reflecting shadowy ethereal landscape",
#     "chic black pantsuit with fitted silhouette",
#     "capsule with red emergency hatch",
#     "vibrant red and gold phoenix figure",
#     "gleaming silver clarinet minimalist shape",
#     "vibrant blue robot towering and muscular",
#     "white dress with blue bow on back",
#     "crystal-embellished rose-gold hairpin sparkling under light",
#     "topaz set in bronze pendant",
#     "cashmere yellow cardigan crew neck",
#     "old spear with chipped tip",
#     "white and red checkerboard chess pieces",
#     "black metal statue of knight riding horse",
#     "a savory dish of vegetables and herbs baked in a seasoned tomato sauce, topped with cheese and breadcrumbs",
#     "vintage bronze drum kit set",
#     "winged humanoid with violet skin and long ears",
#     "dark faceted black diamond",
#     "dark blue robot with oval body",
#     "pewter statue of angels wings spread wide",
#     "clear diamond prism shining on polished silver tray",
#     "iridescent armor for camouflage purposes",
#     "fabric tote bag with multiple pockets and zippers",
#     "teal armchair beside beige ottoman",
#     "white stone kneeling priestess",
#     "small brown garnet with hole in it",
#     "fairy with delicate wings and bright smile",
#     "dappled gray elf wearing intricate cloak",
#     "purple heart-shaped fairy figurine",
#     "dull green cargo train",
#     "rose-pink tourmaline elongated and shiny",
#     "teal screwdriver head phillips head size",
#     "modern glass coffee table near wall",
#     "dinosaur model with yellow spikes",
#     "translucent blue glass bowl smooth interior walls",
#     "violet chair with ochre cushion",
#     "traditional javelin with feathered shaft",
#     "bright yellow lemon cut by metal knife",
#     "wooden robot finger pointing up",
#     "animal that has mane around its neck",
#     "statue wearing long black gown",
#     "crimson wyvern claw glove",
#     "bomb disposal suit sealed tight",
#     "opal anklet featuring wave motifs",
#     "roman glass vase translucent delicate swirls",
#     "chrysanthemum bloom with spots",
#     "stealthy black ninja-robot with hidden blades",
#     "medium-sized pink aluminum spatula",
#     "shiny rifle stock finish",
#     "cloaked figure holding lantern of light",
#     "sturdy dark brown drum kit",
#     "sapphire shard blue iridesc",
#     "black onyx ring looks mysterious",
#     "short blue pitcher",
#     "beast with glowing mane",
#     "apple red scarf",
#     "black leather apron smooth and durable",
#     "weapon with intricate pattern and wooden handle",
#     "roller with red rim",
#     "grand palace with ornate gilded balconies",
#     "orange fiberglass handle pliers",
#     "creamy white pasta dish with side of marinara sauce",
#     "long ears of deer",
#     "crystal-encrusted brooch catching every ray",
#     "cotton tank top with tie-dye effect and scoop neckline",
#     "bright yellow fire truck",
#     "diamond bracelet heart pattern",
#     "gentle unicorn with silver horn standing gracefully",
#     "yellow brush in drawer",
#     "sleek katana featuring reflective blade",
#     "dark blue woolen tunic",
#     "formidable black panther crouched on shadowy rock shelf",
#     "beautiful elf with crown",
#     "navy blue windbreaker hooded zippered pockets",
#     "gold nunchaku balanced and detailed",
#     "creature with gold armor and shields",
#     "white lamp with book on table and apple",
#     "orange triangular note tray",
#     "polished brass crossbow bolt nock",
#     "wooden statue of wise old man",
#     "stylish navy denim overalls adjustable straps",
#     "brooch with diamond clasp",
#     "olive green cricket bat worn edges",
#     "sturdy brick trowel flat and wide",
#     "chic orange scarf warm winter accessory",
#     "ornate wand carved from dark oak wood",
#     "unique orange bag bucket shape",
#     "fashionable purple handbag crafted from high-quality leather",
#     "white minibus rounded edges",
#     "large exhaust fan with blades",
#     "deep purple fae staff",
#     "complex blue motor casing",
#     "metallic blue robot arm industrial red conveyor silver",
#     "brown horned minotaur charging",
#     "dark glossy black piano keys",
#     "giant white creature with long neck and sharp claws",
#     "leather tote bag with handles",
#     "rough red gemstone with inclusions of minerals",
#     "mermaid with iridescent tail curled around coral",
#     "clutch in durable construction",
#     "ceramic dollhouse miniature of quaint victorian tea set",
#     "sleek black vase with curved neck on polished wood table",
#     "brooch of sapphire stars",
#     "dark green emerald pointed and faceted",
#     "deep purple fae staff",
#     "complex blue motor casing",
#     "metallic blue robot arm industrial red conveyor silver",
#     "brown horned minotaur charging",
#     "dark glossy black piano keys",
#     "giant white creature with long neck and sharp claws",
#     "leather tote bag with handles",
#     "rough red gemstone with inclusions of minerals",
#     "mermaid with iridescent tail curled around coral",
#     "clutch in durable construction",
#     "ceramic dollhouse miniature of quaint victorian tea set",
#     "sleek black vase with curved neck on polished wood table",
#     "brooch of sapphire stars",
#     "dark green emerald pointed and faceted",
#     "giant white creature with long neck and sharp claws",
#     "leather tote bag with handles",
#     "rough red gemstone with inclusions of minerals",
#     "mermaid with iridescent tail curled around coral",
#     "clutch in durable construction",
#     "ceramic dollhouse miniature of quaint victorian tea set",
#     "sleek black vase with curved neck on polished wood table",
#     "brooch of sapphire stars",
#     "dark green emerald pointed and faceted",
#     "giant white creature with long neck and sharp claws",
#     "brown marble bathroom vanity top",
#     "compact blue flak jacket",
#     "brown ottoman under shelf",
#     "leather tote bag with handles",
#     "rough red gemstone with inclusions of minerals",
#     "mermaid with iridescent tail curled around coral",
#     "clutch in durable construction",
#     "ceramic dollhouse miniature of quaint victorian tea set",
#     "sleek black vase with curved neck on polished wood table",
#     "brooch of sapphire stars",
#     "dark green emerald pointed and faceted",
#     "crystal spire topped with ruby crown",
#     "abstract dress shirt",
#     "black jiu-jitsu gi folded neatly",
#     "white knife and vegetables",
#     "wide open petal spread",
#     "iron trowel with handle",
#     "angular blue bot with gold hands",
#     "oversized pearl necklace with intricate clasp",
#     "spiral glass tower with rainbow reflections",
#     "soldier in urban camouflage peeking out from building corner",
#     "golden trumpet with glossy reflective finish",
#     "luminous pink topaz cabochon",
#     "vibrant emerald crystal cut into perfect hexagon",
#     "wooden square-shaped saw with metal teeth",
#     "cutting torch mounted on cart",
#     "stone sculpture of reclining figure hands folded",
#     "yellow gun with gold engravings on barrel",
#     "pinstripe blazer showcasing sharp lapels",
#     "vibrant red garnet in glass case",
#     "bracelet made of silver with two rubies on top",
#     "painted clay goddess serene with flowers",
#     "translucent acrylic dolphin leap",
#     "alien-like metallic robot",
#     "robot in chefs hat cooking pasta",
#     "xylophone with ivory and silver color",
#     "blue winged fairy holding golden wand",
#     "brown banshee with long hair flying",
#     "blue spiral-shaped robot crawling on ground",
#     "ivory sofa with armrests and back support",
#     "violet fantasy wand with crystal tip",
#     "yellow medium-sized robot kneeling",
#     "rose gold metal letter opener on desk",
#     "worn-out brown scimitar",
#     "wooden cricket bat polished and glossy",
#     "mystical sphinx with lion body and eagle wings",
#     "orchid with elongated petals in pink",
#     "curved yellow sword",
#     "abstract form with sharp edges",
#     "crystalline star-shaped silver fluorite",
#     "amethyst necklace complementing velvet dress",
#     "robotic arm holding bright orange tool",
#     "pink griffin with golden wings",
#     "candy cane in glass",
#     "dainty gold chain holding single pearl",
#     "bright red battery cover",
#     "elven princess in long flowing white dress",
#     "dark gray minimalist robot",
#     "motorized cart at workbench",
#     "short silver robot antenna",
#     "intricately carved wooden totem pole",
#     "little black chain",
#     "sturdy metallic blue pliers",
#     "orange glass filled with orange juice above",
#     "burgundy pliers insulated handles",
#     "dark gray cylindrical body",
#     "small white alien with blue eyes",
#     "translucent blue-tinted jagged crystal",
#     "small metal chisel with green handle",
#     "pink drill with metallic shaft",
#     "arrow with silver shaft and black head",
#     "white fairy with iridescent wings and wand",
#     "plastic-handled screwdriver bright orange color",
#     "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
#     "blue mermaid with scales made",
#     "antique ivory curved harp strings",
#     "matte gray military military dagger",
#     "thick gold bracelet with large square green gemstone in center",
#     "metal drill with black handle and blue tip",
#     "soldier holding rifle standing",
#     "pastel pink silk-draped chaise lounge",
#     "mystical purple amulet with symbols",
#     "leather-bound ornate crossbow with flintlock",
#     "silver necklace with red zircon",
#     "golden locket with intricate pattern",
#     "futuristic plasma gun with energy core",
#     "ornate brass candle holder with flickering flame",
#     "small wooden hammer with screws",
#     "orange metal pliers with long handles",
#     "white bolt with hexagonal shape",
#     "gold chain with infinity symbol and cross pendant",
#     "pink alien with tentacles on its head",
#     "large pink stone on black background",
#     "purple heart-shaped keychain on leather strap",
#     "small purple alien with large eyes and long tongue",
#     "robot that is standing on table",
#     "stylish yellow sneakers modern",
#     "plastic bucket bright red with white stripes",
#     "mythical crystal staff with magical runes",
#     "harp with white strings and gold tuning pegs",
#     "purple tall robot with single arm",
#     "shimmering gold violin with pearl inlay",
#     "turquoise necklace with large gemstone",
#     "traditional wooden staff adorned with runes",
#     "pixie with wand",
#     "dark green minivan sliding door wide",
#     "thick yellow plastic spoon",
#     "toy bear with hat",
#     "vintage clarinet in rich dark stain",
#     "dark green pickup truck with cargo bed cover",
#     "gray robot with two round eyes",
#     "small brass candlestick holder with spiral",
#     "magical potion bottle with starry label",
#     "classic fedora hat in rich brown leather",
#     "ruby bracelet with unique twisted band",
#     "yellow screwdriver with short handle",
#     "yellow and white checkered robot pose",
#     "shiny silver spherical robot with smooth finish",
#     "glass statue abstract with flowing shapes",
#     "glossy gold harp luxurious and enchanting",
#     "violet succubus with long",
#     "small chisel with black tip",
#     "deep navy robot with sophisticated style",
#     "glistening yellow citrine prism",
#     "large blue crystal with irregular shape and sharp edges",
#     "yellow lamp with bent neck",
#     "vibrant red vase with elegant swirl",
#     "small purple cylindrical creature with short tail and long legs",
#     "silver robot wearing green scarf",
#     "warm yellow woolen scarf with fringed edges",
#     "ruby bracelet adorned with faceted stones",
#     "purple suv high roof off-road tires",
#     "sapphire mace with gold-plated head",
#     "teal camper van rooftop tent and awning",
#     "teal suv with",
#     "silver pendant necklace featuring infinity symbol",
#     "glossy blue clarinet straight body",
#     "lustrous black hockey stick slashing",
#     "robot in sitting down position",
#     "mystical orb pulsating with arcane energy",
#     "small winged fairy with golden wings",
#     "parachute deployed mid-air high-speed descent",
#     "metallic robot turning right",
#     "colorful candy in clear glass bottle",
#     "black knight armored in shadow",
#     "magical lantern casting soft blue glow",
#     "purple sapphire in necklace",
#     "white pear delicate texture slightly translucent",
#     "rose quartz heart pendant symbolizing love",
#     "glossy blue glass candle holder elegant",
#     "orange electric sander with variable speed",
#     "polished steel drums bright and tropical",
#     "glimmering orange agate with wavy pattern",
#     "heavy-duty green plasma rifle",
#     "amethyst anklet with swirling vine-like patterns",
#     "copper measuring tape retractable",
#     "metal scissors with two sharp blades and curved shape",
#     "red triangle with black circle on it",
#     "smooth purple lacrosse stick",
#     "dark steel knife serrated edge and pointed tip",
#     "ornate bronze cannon with curved barrel",
#     "red and blue monkey with long tail",
#     "silver glowing mermaid",
#     "luxurious cream sedan elegant",
#     "stone statue ancient warrior in battle pose",
#     "jade dragon scale crossbow",
#     "blue sharp-edged katana at angle",
#     "grey and white pliers",
#     "sapphire bracelet adorned with small gleaming stones",
#     "clarinet with green covering",
#     "heavy-duty gray sledgehammer with leather head",
#     "crunchy salted pretzel in bag",
#     "transparent crystal with blue color",
#     "black and silver pliers",
#     "vibrant drum kit red cymbals metallic snares",
#     "stud earrings small hoops shiny surface",
#     "maroon triangular coaster under cup",
#     "purple gun with silencer and metal barrel",
#     "platinum earrings capturing fires glow",
#     "bronze halberd with twisted iron blade",
#     "gold charm bracelet with lock",
#     "gray drill with silver bit",
#     "classic wood chisel with polished tip",
#     "sparkling hexagonal topaz prism",
#     "blue pen holder with clips",
#     "elegant gold candlestick holder with intricate details",
#     "small blue creature with short legs and long nose",
#     "platter adorned with sliced turkey breast",
#     "glossy black olive within glass bowl",
#     "bright orange delivery van with open tailgate",
#     "big wooden spoon for stirring",
#     "dark green golf club head with yellow shaft",
#     "orcs iron helmet with spikes",
#     "shiny brass candle holder twin flames",
#     "jack in industrial",
#     "wooden coffee table with diamond-shaped top",
#     "lacrosse stick yellow and black head",
#     "translucent blue topaz perched on sleek metal stand",
#     "tall slender glass filled with iced lemonade",
#     "bright pink minivan with floral pattern",
#     "small red plastic screwdriver ergonomic",
#     "tiny pink buds on early spring branch",
#     "emerald green and gold bangle",
#     "knee guards of dark blue",
#     "short purple bipedal creature with long neck and small wings",
#     "vintage ivory keys piano on stand",
#     "onyx hairpin with tiny diamonds",
#     "tall ornate wood clarinet",
#     "automatic rifle with olive green stock",
#     "ornate harp with set of strings and polished",
#     "large metal dagger with ivory handle",
#     "sapphire cufflinks with silver band",
#     "shiny copper robot arm",
#     "small spear with emerald",
#     "steel drum with multicolored patterns and shiny surface",
#     "pixie dancing on bed of stars",
#     "small blue donut with chocolate frosting and sprinkles",
#     "transparent segmented shell with iridescent edges",
#     "green four-legged creature with large ears",
#     "green harp standing tall in corner",
#     "yellow robot carrying blue toolbox",
#     "centaur holding bow standing poised",
#     "classic yellow bus with retro",
#     "leather-bound black bookshelf tall stature",
#     "claymore sword engraved with celtic patterns",
#     "large oval-shaped with pointed edges and rough texture blue gem stone",
#     "brown wooden shutters set",
#     "pink metal wrench with adjustable spanner",
#     "delicate harp with curved neck",
#     "smokey quartz candlestick holder",
#     "glass statue of abstract shape with texture",
#     "intricately carved bow in walnut wood",
#     "giant marble statue man standing sword raised",
#     "ornate gold ring set with sapphire",
#     "glass wine glass with stem",
#     "obsidian mirror reflecting ethereal shifting landscape",
#     "obsidian shard smooth black sheen",
#     "single stem of lavender with purple buds",
#     "pendant with oval shape and white pearls",
#     "tiny green goblin clutching large red gem",
#     "scissor jack in garage",
#     "purple and long level rod",
#     "onyx choker with central drop",
#     "spiraling tower made of iridescent rainbow-hued glass",
#     "lustrous diamond shard clear and pointed",
#     "delicate pearl necklace featuring heart pendant",
#     "crunchy salted pretzel in tin",
#     "sharp bronze throwing spear",
#     "smooth curved cricket bat waiting for impact",
#     "slate cherub holding olive branch above head",
#     "hockey stick with tape and blade",
#     "pale green peridot stone in bronze bowl",
#     "octagonal shiny control panel",
#     "sleek futuristic pistol with holographic display",
#     "purple and pink polka-dotted droid",
#     "smooth and round shaped gem",
#     "carbon fiber sniper rifle matte black finish scope attached",
#     "robot that is energetic and dynamic",
#     "white plastic baseball bat standing",
#     "staff with glowing runes and mystical powers",
#     "shimmering unicorn horn ornament",
#     "pearl pendant on silk cord",
#     "colorful glass beads in clear glass bottle",
#     "green goblin with horns fangs and pointed ears",
#     "blue diamond with inclusion",
#     "green olive stuffed in cocktail stick",
#     "rose quartz hairpin in rose",
#     "gray dartboard on stand",
#     "heavy-duty steel cricket bat with engraved logo",
#     "glossy blue futuristic laser pistol",
#     "metal screwdriver bent tip",
#     "unique purple sedan with unique wheel designs",
#     "emerald bracelet delicate engraved",
#     "dark granite statue depicting warrior with spear",
#     "small blueberry in basket",
#     "rough purple diamond-shaped gem",
#     "small green hammer with oval head",
#     "large pink irregular shaped stone",
#     "terracotta priestess dancing with flowing robes",
#     "shiny tourmaline multicolored cylindrical",
#     "iridescent opal slice showing rainbow colors in sunlight",
#     "moonstone bracelet with silver clasp mechanism",
#     "topaz stone golden shine",
#     "scissors curved blades sharp",
#     "sturdy brown cargo van cargo bay door",
#     "intricate ivory mace ornate head",
#     "glow-in-the-dark star-shaped pendant on chain",
#     "knight shield with lion embossed",
#     "frosted turquoise triangular gem",
#     "solution crystal clear blue sapphire pendant",
#     "wooden clarinet antique look",
#     "whimsical windmill turning slowly in breeze",
#     "axe with axe head and wooden handle and metal",
#     "large green sharp axe",
#     "saxophone with gold keys and silver",
#     "orange fire truck ladder extended high",
#     "banjo with wooden body and strings made of metal wire or nylon string",
#     "black toy boat sailed",
#     "black metal sturdy shovel",
#     "thin brown vase",
#     "large smooth amethyst crystal",
#     "scissor cutters in white color",
#     "large blue drill bit for metal",
#     "vintage steel press machine",
#     "red sandstone statue of soldier",
#     "jade pendant resting on leather cord",
#     "vibrant rainbow-colored gelato scoop melting slightly",
#     "small plastic basket with yellow handle",
#     "burnished bronze spearhead sharp",
#     "translucent quartz crystal with clear faceted appearance",
#     "elegant clarinet in polished wood",
#     "ripe banana hanging by string from ceiling",
#     "ivory harp hanging on wall",
#     "purple ukulele small guitar-like shape",
#     "feathered quiver holding arrows of various",
#     "large wooden tennis racket",
#     "jeweled scimitar with flowing emerald inlay patterns",
#     "green crooked golf club head",
#     "metal screwdriver straight shaft",
#     "vibrant orange cone-shaped robot",
#     "translucent quartz crystal with clear facets",
#     "steel drum tropical pattern",
#     "bright yellow saxophone with smooth keys",
#     "cube-shaped bot in matte-black",
#     "white table with three chairs and plant on it",
#     "golden harp with delicate filigree detailing",
#     "boxing glove with red stripes and white lining",
#     "matte blue turquoise fragment",
#     "dark green leafy branch",
#     "big clear brown stone",
#     "tiny robot with round yellow eyes",
#     "large square silver bracelet with sapphire in corner",
#     "bow with green wood body and white string",
#     "multi-colored vibrant agate slice",
#     "centaur archer poised bowstring taut aiming skyward",
#     "polished rosewood clarinet in sheath",
#     "cracked obsidian ancient spearhead",
#     "plastic straw of drink",
#     "small yellow triangular wooden kitchen knife",
#     "ukulele sporting vibrant sunflower yellow",
#     "white elf holding ancient golden staff",
#     "purple troll with long hair and green",
#     "long narrow black drill",
#     "modern futuristic assault rifle",
#     "velvet green sofa with gold piping",
#     "sharp red bayonet on rifle",
#     "statue of animal flying on pedestal",
#     "banana split with toppings",
#     "large shiny silver screwdriver",
#     "glass vase with intricate blue patterns",
#     "huge pink dinosaur with blue spots",
#     "deep green emerald sleek cut",
#     "charming pink minivan sporting floral decals",
#     "sleek blue cricket bat poised",
#     "lime green golf club",
#     "eggshell green metal screwdriver with silver handle",
#     "robot with red and blue stripes in crate",
#     "sturdy plastic bucket bright yellow color useful for painting",
#     "whole wheat pizza with extra cheese",
#     "green alien with large head and big eyes",
#     "green hammer with wood",
#     "matte-black octahedral robot with sharp edges",
#     "robot with orange star shape",
#     "small white square-shaped quartz crystal with gold chain", #<---
#     "amethyst teardrop-shaped earrings set in gold",
#     "blue polycarbonate drill bit",
#     "greek amphora scene detail",
#     "necklace with opals in it",
#     "harmonica in classic matte black",
#     "rose gold locket necklace with floral",
#     "robot with olive green circle shape",
#     "green sports car sleek aerodynamic",
#     "glossy blue saxophone with sleek lines",
#     "small and oval shaped black gemstone with rough surface and dark color",
#     "green leafy staff with heart-shaped handle",
#     "bright orange baseball bat with intricate wood grain",
#     "limestone figure of dancing faun",
#     "heavy-duty wrench black and yellow stripes",
#     "gold-trimmed sword elegant curve",
#     "lightweight white chisel with pointed end",
#     "radiant heart-shaped opal necklace",
#     "large golden trowel",
#     "green squash racket streamlined", # <--
#     "dull irregular quartz crystal",
#     "sturdy metal screwdriver tip pointed blue handle",
#     "black clarinet classic and timeless",
#     "green rubber gloves pack",
#     "sleek green marimba",
#     "glowing tower with spiraling silver staircases",
#     "matte black bass guitar with sleek modern",
#     "blue putty knife flat surface",
#     "white ice cube tray",
#     "antique silver candlestick two-pronged",
#     "old-fashioned hammer with black head",
#     "matte blue cricket bat stands ready",
#     "drill bit yellow slender pointed tip",
#     "onyx helmet crowned by sapphire crest",
#     "textured jasper mineral chunk",
#     "polished silver clarinet with elegant",
#     "golden intricate long crossbow",
#     "dark green van reversing now",
#     "silver serpent coiled around glowing crystal staff",
#     "saxophone mouthpiece in elegant silver",
#     "white wooden golf club head",
#     "enormous black robot with round body",
#     "bow with green handle and yellow bow",
#     "wooden flute adorned with colorful beads",
#     "glowing staff topped with radiant sapphire stone",
#     "sapphire-studded sharp spear",
#     "emerald pendant",
#     "bottle of red wine with cork in it",
#     "crystal staff with swirling light",
#     "harp adorned with pearl inlays and gilded frame",
#     "necklace with heart-shaped pendant made of silver and turquoise stones",
#     "cupcake with chocolate icing on top",
#     "matte black candle holder two interlocking pieces",
#     "greek kylix cup black-figure technique mythological scenes",
#     "small round blue creature with long nose and pointed ears",
#     "tall glass of layered lemonade",
#     "cylindrical glass of bubbly lemonade",
#     "small pink robot with round eyes and metal arms",
#     "aquamarine hairpin with spiral form",
#     "ivory maiden with lute",
#     "white van cargo boxes subarban",
#     "green hexagonal torso on robot",
#     "organge plastic cup with two handles on either side of cup",
#     "yellow robot with shiny metallic surface",
#     "pink frosted donus hold on stick",
#     "short green creature with long tail and sharp claws",
#     "diamond suspended by platinum chain"
# ]


# EPISODIC_TEST_PROMPTS = [
#     "orchid with elongated petals in pink",
#     "curved yellow sword",
#     "abstract form with sharp edges",
#     "crystalline star-shaped silver fluorite",
#     "amethyst necklace complementing velvet dress",
#     "robotic arm holding bright orange tool",
#     "pink griffin with golden wings",
#     "candy cane in glass",
#     "dainty gold chain holding single pearl",
#     "bright red battery cover",
#     "elven princess in long flowing white dress",
#     "dark gray minimalist robot",
#     "motorized cart at workbench",
#     "short silver robot antenna",
#     # "matte blue cricket bat stands ready",
#     # "drill bit yellow slender pointed tip",
#     # "onyx helmet crowned by sapphire crest",
#     # "textured jasper mineral chunk",
#     # "polished silver clarinet with elegant",
#     # "golden intricate long crossbow",
#     # "dark green van reversing now",
#     # "silver serpent coiled around glowing crystal staff",
#     # "saxophone mouthpiece in elegant silver",
#     # "white wooden golf club head",
#     # "enormous black robot with round body",
#     # "bow with green handle and yellow bow",
#     # "wooden flute adorned with colorful beads",
#     # "glossy blue clarinet straight body",
#     # "lustrous black hockey stick slashing",
#     "intricately carved wooden totem pole",
#     "little black chain",
#     "sturdy metallic blue pliers",
#     "orange glass filled with orange juice above",
#     "burgundy pliers insulated handles",
#     "dark gray cylindrical body",
#     "small white alien with blue eyes",
#     "translucent blue-tinted jagged crystal",
#     "small metal chisel with green handle",
#     "pink drill with metallic shaft",
#     "arrow with silver shaft and black head",
#     "white fairy with iridescent wings and wand",
#     "plastic-handled screwdriver bright orange color",
#     "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
#     "blue mermaid with scales made",
#     "antique ivory curved harp strings",
#     "matte gray military military dagger",
#     "thick gold bracelet with large square green gemstone in center",
#     "metal drill with black handle and blue tip",
#     "soldier holding rifle standing",
#     "pastel pink silk-draped chaise lounge",
#     "mystical purple amulet with symbols",
#     # "leather-bound ornate crossbow with flintlock",
#     # "silver necklace with red zircon",
#     # "golden locket with intricate pattern",
#     # "futuristic plasma gun with energy core",
#     # "ornate brass candle holder with flickering flame",
#     # "small wooden hammer with screws",
#     # "orange metal pliers with long handles",
#     # "white bolt with hexagonal shape",
#     # "gold chain with infinity symbol and cross pendant",
#     # "pink alien with tentacles on its head",
#     # "large pink stone on black background",
#     # "purple heart-shaped keychain on leather strap",
#     # "small purple alien with large eyes and long tongue",
#     # "robot that is standing on table",
#     # "stylish yellow sneakers modern",
#     # "plastic bucket bright red with white stripes",
#     # "mythical crystal staff with magical runes",
#     # "harp with white strings and gold tuning pegs",
#     # "purple tall robot with single arm",
#     # "shimmering gold violin with pearl inlay",
#     # "turquoise necklace with large gemstone",
#     # "traditional wooden staff adorned with runes",
#     # "pixie with wand",
#     # "dark green minivan sliding door wide",
#     # "thick yellow plastic spoon",
#     # "toy bear with hat",
#     # "vintage clarinet in rich dark stain",
#     # "dark green pickup truck with cargo bed cover",
#     # "gray robot with two round eyes",
#     # "small brass candlestick holder with spiral",
#     # "magical potion bottle with starry label",
#     # "classic fedora hat in rich brown leather",
#     # "ruby bracelet with unique twisted band",
#     # "yellow screwdriver with short handle",
#     # "yellow and white checkered robot pose",
#     # "shiny silver spherical robot with smooth finish",
#     # "glass statue abstract with flowing shapes",
#     # "glossy gold harp luxurious and enchanting",
#     # "violet succubus with long",
#     # "small chisel with black tip",
#     # "deep navy robot with sophisticated style", 
#     # "glistening yellow citrine prism", 
#     # "large blue crystal with irregular shape and sharp edges", 
#     # "yellow lamp with bent neck",
#     # "vibrant red vase with elegant swirl",
#     # "small purple cylindrical creature with short tail and long legs",
#     # "silver robot wearing green scarf",
#     # "warm yellow woolen scarf with fringed edges",
#     # "ruby bracelet adorned with faceted stones",
#     # "purple suv high roof off-road tires",
#     # "sapphire mace with gold-plated head",
#     # "teal camper van rooftop tent and awning",
#     # "teal suv with",
#     # "silver pendant necklace featuring infinity symbol",
#     # "glossy blue clarinet straight body",
#     # "lustrous black hockey stick slashing",
#     # "intricately carved wooden totem pole",
#     # "little black chain",
#     # "sturdy metallic blue pliers",
#     # "orange glass filled with orange juice above",
#     # "burgundy pliers insulated handles",
#     # "dark gray cylindrical body",
#     # "small white alien with blue eyes",
#     # "translucent blue-tinted jagged crystal",
#     # "small metal chisel with green handle",
#     # "pink drill with metallic shaft",
#     # "arrow with silver shaft and black head",
#     # "white fairy with iridescent wings and wand",
#     # "plastic-handled screwdriver bright orange color",
#     # "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
#     # "blue mermaid with scales made",
#     # "antique ivory curved harp strings",
#     # "matte gray military military dagger",
#     # "thick gold bracelet with large square green gemstone in center",
#     # "metal drill with black handle and blue tip",
#     # "soldier holding rifle standing",
#     # "pastel pink silk-draped chaise lounge",
#     # "mystical purple amulet with symbols",
#     # "leather-bound ornate crossbow with flintlock",
#     # "silver necklace with red zircon",
#     # "golden locket with intricate pattern",
#     # "futuristic plasma gun with energy core",
#     # "ornate brass candle holder with flickering flame",
#     # "small wooden hammer with screws",
#     # "orange metal pliers with long handles",
#     # "white bolt with hexagonal shape",
#     # "gold chain with infinity symbol and cross pendant",
#     # "pink alien with tentacles on its head",
#     # "large pink stone on black background",
#     # "robot in sitting down position",
#     # "mystical orb pulsating with arcane energy",
#     # "small winged fairy with golden wings",
#     # "parachute deployed mid-air high-speed descent",
#     # "metallic robot turning right",
#     # "colorful candy in clear glass bottle",
#     # "black knight armored in shadow",
#     # "magical lantern casting soft blue glow",
#     # "purple sapphire in necklace",
#     # "white pear delicate texture slightly translucent",
#     # "rose quartz heart pendant symbolizing love",
#     # "glossy blue glass candle holder elegant",
#     # "orange electric sander with variable speed",
#     # "polished steel drums bright and tropical",
#     # "glimmering orange agate with wavy pattern",
#     # "heavy-duty green plasma rifle",
#     # "amethyst anklet with swirling vine-like patterns",
#     # "copper measuring tape retractable",
#     # "metal scissors with two sharp blades and curved shape",
#     # "red triangle with black circle on it",
#     # "smooth purple lacrosse stick",
#     # "dark steel knife serrated edge and pointed tip",
#     # "ornate bronze cannon with curved barrel",
#     # "red and blue monkey with long tail",
#     # "silver glowing mermaid",
#     # "luxurious cream sedan elegant",
#     # "stone statue ancient warrior in battle pose",
#     # "jade dragon scale crossbow",
#     # "blue sharp-edged katana at angle",
#     # "grey and white pliers",
#     # "sapphire bracelet adorned with small gleaming stones",
#     # "clarinet with green covering",
#     # "heavy-duty gray sledgehammer with leather head",
#     # "crunchy salted pretzel in bag",
#     # "transparent crystal with blue color",
#     # "black and silver pliers",
#     # "vibrant drum kit red cymbals metallic snares",
#     # "stud earrings small hoops shiny surface",
#     # "maroon triangular coaster under cup",
#     # "purple gun with silencer and metal barrel",
#     # "platinum earrings capturing fires glow",
#     # "bronze halberd with twisted iron blade",
#     # "gold charm bracelet with lock",
#     # "gray drill with silver bit",
#     # "classic wood chisel with polished tip",
#     # "sparkling hexagonal topaz prism",
#     # "blue pen holder with clips",
#     # "elegant gold candlestick holder with intricate details",
#     # "small blue creature with short legs and long nose",
#     # "platter adorned with sliced turkey breast",
#     # "glossy black olive within glass bowl",
#     # "bright orange delivery van with open tailgate",
#     # "big wooden spoon for stirring",
#     # "dark green golf club head with yellow shaft",
#     # "orcs iron helmet with spikes",
#     # "shiny brass candle holder twin flames",
#     # "jack in industrial",
#     # "wooden coffee table with diamond-shaped top",
#     # "lacrosse stick yellow and black head",
#     # "translucent blue topaz perched on sleek metal stand",
#     # "tall slender glass filled with iced lemonade",
#     # "bright pink minivan with floral pattern",
#     # "small red plastic screwdriver ergonomic",
#     # "tiny pink buds on early spring branch",
#     # "emerald green and gold bangle",
#     # "knee guards of dark blue",
#     # "short purple bipedal creature with long neck and small wings",
#     # "vintage ivory keys piano on stand",
#     # "onyx hairpin with tiny diamonds",
#     # "tall ornate wood clarinet",
#     # "automatic rifle with olive green stock",
#     # "ornate harp with set of strings and polished",
#     # "large metal dagger with ivory handle",
#     # "sapphire cufflinks with silver band",
#     # "shiny copper robot arm",
#     # "small spear with emerald",
#     # "steel drum with multicolored patterns and shiny surface",
#     # "pixie dancing on bed of stars",
#     # "small blue donut with chocolate frosting and sprinkles",
#     # "transparent segmented shell with iridescent edges",
#     # "green four-legged creature with large ears",
#     # "green harp standing tall in corner",
#     # "yellow robot carrying blue toolbox",
#     # "centaur holding bow standing poised",
#     # "classic yellow bus with retro",
#     # "leather-bound black bookshelf tall stature",
#     # "claymore sword engraved with celtic patterns",
#     # "large oval-shaped with pointed edges and rough texture blue gem stone",
#     # "brown wooden shutters set",
#     # "pink metal wrench with adjustable spanner",
#     # "delicate harp with curved neck",
#     # "smokey quartz candlestick holder",
#     # "glass statue of abstract shape with texture",
#     # "intricately carved bow in walnut wood",
#     # "giant marble statue man standing sword raised",
#     # "ornate gold ring set with sapphire",
#     # "glass wine glass with stem",
#     # "obsidian mirror reflecting ethereal shifting landscape",
#     # "obsidian shard smooth black sheen",
#     # "single stem of lavender with purple buds",
#     # "pendant with oval shape and white pearls",
#     # "tiny green goblin clutching large red gem",
#     # "scissor jack in garage",
#     # "purple and long level rod",
#     # "onyx choker with central drop",
#     # "spiraling tower made of iridescent rainbow-hued glass",
#     # "lustrous diamond shard clear and pointed",
#     # "delicate pearl necklace featuring heart pendant",
#     # "crunchy salted pretzel in tin",
#     # "sharp bronze throwing spear",
#     # "smooth curved cricket bat waiting for impact",
#     # "slate cherub holding olive branch above head",
#     # "hockey stick with tape and blade",
#     # "pale green peridot stone in bronze bowl",
#     # "octagonal shiny control panel",
#     # "sleek futuristic pistol with holographic display",
#     # "purple and pink polka-dotted droid",
#     # "smooth and round shaped gem",
#     # "carbon fiber sniper rifle matte black finish scope attached",
#     # "robot that is energetic and dynamic",
#     # "white plastic baseball bat standing",
#     # "staff with glowing runes and mystical powers",
#     # "shimmering unicorn horn ornament",
#     # "pearl pendant on silk cord",
#     # "colorful glass beads in clear glass bottle",
#     # "green goblin with horns fangs and pointed ears",
#     # "blue diamond with inclusion",
#     # "green olive stuffed in cocktail stick",
#     # "rose quartz hairpin in rose",
#     # "gray dartboard on stand",
#     # "heavy-duty steel cricket bat with engraved logo",
#     # "glossy blue futuristic laser pistol",
#     # "metal screwdriver bent tip",
#     # "unique purple sedan with unique wheel designs",
#     # "emerald bracelet delicate engraved",
#     # "dark granite statue depicting warrior with spear",
#     # "small blueberry in basket",
#     # "rough purple diamond-shaped gem",
#     # "small green hammer with oval head",
#     # "large pink irregular shaped stone",
#     # "terracotta priestess dancing with flowing robes",
#     # "shiny tourmaline multicolored cylindrical",
#     # "iridescent opal slice showing rainbow colors in sunlight",
#     # "moonstone bracelet with silver clasp mechanism",
#     # "topaz stone golden shine",
#     # "scissors curved blades sharp",
#     # "sturdy brown cargo van cargo bay door",
#     # "intricate ivory mace ornate head",
#     # "glow-in-the-dark star-shaped pendant on chain",
#     # "knight shield with lion embossed",
#     # "frosted turquoise triangular gem",
#     # "solution crystal clear blue sapphire pendant",
#     # "wooden clarinet antique look",
#     # "whimsical windmill turning slowly in breeze",
#     # "axe with axe head and wooden handle and metal",
#     # "large green sharp axe",
#     # "saxophone with gold keys and silver",
#     # "orange fire truck ladder extended high",
#     # "banjo with wooden body and strings made of metal wire or nylon string",
#     # "black toy boat sailed",
#     # "black metal sturdy shovel",
#     # "thin brown vase",
#     # "large smooth amethyst crystal",
#     # "scissor cutters in white color",
#     # "large blue drill bit for metal",
#     # "vintage steel press machine",
#     # "red sandstone statue of soldier",
#     # "jade pendant resting on leather cord",
#     # "vibrant rainbow-colored gelato scoop melting slightly",
#     # "small plastic basket with yellow handle",
#     # "burnished bronze spearhead sharp",
#     # "translucent quartz crystal with clear faceted appearance",
#     # "elegant clarinet in polished wood",
#     # "ripe banana hanging by string from ceiling",
#     # "ivory harp hanging on wall",
#     # "purple ukulele small guitar-like shape",
#     # "feathered quiver holding arrows of various",
#     # "large wooden tennis racket",
#     # "jeweled scimitar with flowing emerald inlay patterns",
#     # "green crooked golf club head",
#     # "metal screwdriver straight shaft",
#     # "vibrant orange cone-shaped robot",
#     # "translucent quartz crystal with clear facets",
#     # "steel drum tropical pattern",
#     # "bright yellow saxophone with smooth keys",
#     # "cube-shaped bot in matte-black",
#     # "white table with three chairs and plant on it",
#     # "golden harp with delicate filigree detailing",
#     # "boxing glove with red stripes and white lining",
#     # "matte blue turquoise fragment",
#     # "dark green leafy branch",
#     # "big clear brown stone",
#     # "tiny robot with round yellow eyes",
#     # "large square silver bracelet with sapphire in corner",
#     # "bow with green wood body and white string",
#     # "multi-colored vibrant agate slice",
#     # "centaur archer poised bowstring taut aiming skyward",
#     # "polished rosewood clarinet in sheath",
#     # "cracked obsidian ancient spearhead",
#     # "plastic straw of drink", # start test 
#     # "small yellow triangular wooden kitchen knife",
#     # "ukulele sporting vibrant sunflower yellow",
#     # "white elf holding ancient golden staff",
#     # "purple troll with long hair and green",
#     # "long narrow black drill",
#     # "modern futuristic assault rifle",
#     # "velvet green sofa with gold piping",
#     # "sharp red bayonet on rifle",
#     # "statue of animal flying on pedestal",
#     # "banana split with toppings",
#     # "large shiny silver screwdriver",
#     # "glass vase with intricate blue patterns",
#     # "huge pink dinosaur with blue spots",
#     # "deep green emerald sleek cut",
#     # "charming pink minivan sporting floral decals",
#     # "sleek blue cricket bat poised",
#     # "lime green golf club",
#     # "eggshell green metal screwdriver with silver handle",
#     # "robot with red and blue stripes in crate",
#     # "sturdy plastic bucket bright yellow color useful for painting",
#     # "whole wheat pizza with extra cheese",
#     # "green alien with large head and big eyes",
#     # "green hammer with wood",
#     # "matte-black octahedral robot with sharp edges",
#     # "robot with orange star shape",
#     # "small white square-shaped quartz crystal with gold chain",
#     # "amethyst teardrop-shaped earrings set in gold",
#     # "blue polycarbonate drill bit",
#     # "greek amphora scene detail",
#     # "necklace with opals in it",
#     # "harmonica in classic matte black",
#     # "rose gold locket necklace with floral",
#     # "robot with olive green circle shape",
#     # "green sports car sleek aerodynamic",
#     # "glossy blue saxophone with sleek lines",
#     # "small and oval shaped black gemstone with rough surface and dark color",
#     # "green leafy staff with heart-shaped handle",
#     # "bright orange baseball bat with intricate wood grain",
#     # "limestone figure of dancing faun",
#     # "heavy-duty wrench black and yellow stripes",
#     # "gold-trimmed sword elegant curve",
#     # "lightweight white chisel with pointed end",
#     # "radiant heart-shaped opal necklace",
#     # "large golden trowel",
#     # "green squash racket streamlined",
#     # "dull irregular quartz crystal",
#     # "sturdy metal screwdriver tip pointed blue handle",
#     # "black clarinet classic and timeless",
#     # "green rubber gloves pack",
#     # "sleek green marimba",
#     # "glowing tower with spiraling silver staircases",
#     # "matte black bass guitar with sleek modern",
#     # "blue putty knife flat surface",
#     # "white ice cube tray",
#     # "antique silver candlestick two-pronged",
#     # "old-fashioned hammer with black head",
#     # "matte blue cricket bat stands ready",
#     # "drill bit yellow slender pointed tip",
#     # "onyx helmet crowned by sapphire crest",
#     # "textured jasper mineral chunk",
#     # "polished silver clarinet with elegant",
#     # "golden intricate long crossbow",
#     # "dark green van reversing now",
#     # "silver serpent coiled around glowing crystal staff",
#     # "saxophone mouthpiece in elegant silver",
#     # "white wooden golf club head",
#     # "enormous black robot with round body",
#     # "bow with green handle and yellow bow",
#     # "wooden flute adorned with colorful beads",
#     # "glowing staff topped with radiant sapphire stone",# --- end test 
#     # "glossy blue clarinet straight body",
#     # "lustrous black hockey stick slashing",
#     # "intricately carved wooden totem pole",
#     # "little black chain",
#     # "sturdy metallic blue pliers",
#     # "orange glass filled with orange juice above",
#     # "burgundy pliers insulated handles",
#     # "dark gray cylindrical body",
#     # "small white alien with blue eyes",
#     # "translucent blue-tinted jagged crystal",
#     # "small metal chisel with green handle",
#     # "pink drill with metallic shaft",
#     # "arrow with silver shaft and black head",
#     # "white fairy with iridescent wings and wand",
#     # "plastic-handled screwdriver bright orange color",
#     # "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
#     # "blue mermaid with scales made",
#     # "antique ivory curved harp strings",
#     # "matte gray military military dagger",
#     # "thick gold bracelet with large square green gemstone in center",
#     # "metal drill with black handle and blue tip",
#     # "soldier holding rifle standing",
#     # "pastel pink silk-draped chaise lounge",
#     # "mystical purple amulet with symbols",
#     # "leather-bound ornate crossbow with flintlock",
#     # "silver necklace with red zircon",
#     # "golden locket with intricate pattern",
#     # "futuristic plasma gun with energy core",
#     # "ornate brass candle holder with flickering flame",
#     # "small wooden hammer with screws",
#     # "orange metal pliers with long handles",
#     # "sapphire-studded sharp spear",
#     # "emerald pendant", 
#     # "bottle of red wine with cork in it",
#     # "crystal staff with swirling light",
#     # "harp adorned with pearl inlays and gilded frame",
#     # "necklace with heart-shaped pendant made of silver and turquoise stones",
#     # "bottle of red wine with cork in it",
#     # "cupcake with chocolate icing on top", 
#     # "matte black candle holder two interlocking pieces",
#     # "greek kylix cup black-figure technique mythological scenes",
#     # "small round blue creature with long nose and pointed ears",
#     # "tall glass of layered lemonade",
#     # "cylindrical glass of bubbly lemonade"
#     # "example prompt (commented out)",
#     # "large pink stone on black background",
#     # "pink alien with tentacles on its head",
#     # "gold chain with infinity symbol and cross pendant",
#     # "white bolt with hexagonal shape",
#     # "small pink robot with round eyes and metal arms",
#     # "aquamarine hairpin with spiral form",
#     # "ivory maiden with lute",
#     # "white van cargo boxes subarban",
#     # "green hexagonal torso on robot",
#     # "organge plastic cup with two handles on either side of cup",
#     # "yellow robot with shiny metallic surface",
#     # "pink frosted donus hold on stick",
#     # "short green creature with long tail and sharp claws",
#     # "diamond suspended by platinum chain"
# ] 

# Episodic test prompts for optimizer
# Comment out any prompt you do not want to use.
# This file is auto-updated to add new 0-fidelity prompts, but never removes any.
