# Episodic test prompts for optimizer
# Comment out any prompt you do not want to use.
# This file is auto-updated to add new 0-fidelity prompts, but never removes any.

EPISODIC_TEST_PROMPTS = [
    "drill bit yellow slender pointed tip",
    "onyx helmet crowned by sapphire crest",
    "textured jasper mineral chunk",
    "polished silver clarinet with elegant",
    "golden intricate long crossbow",
    "dark green van reversing now",
    "silver serpent coiled around glowing crystal staff",
    "saxophone mouthpiece in elegant silver",
    "white wooden golf club head",
    "enormous black robot with round body",
    "bow with green handle and yellow bow",
    "wooden flute adorned with colorful beads",
    "glossy blue clarinet straight body",
    "lustrous black hockey stick slashing",
    "intricately carved wooden totem pole",
    "little black chain",
    "sturdy metallic blue pliers",
    "orange glass filled with orange juice above",
    "burgundy pliers insulated handles",
    "dark gray cylindrical body",
    "small white alien with blue eyes",
    "translucent blue-tinted jagged crystal",
    "small metal chisel with green handle",
    "pink drill with metallic shaft",
    "arrow with silver shaft and black head",
    "white fairy with iridescent wings and wand",
    "plastic-handled screwdriver bright orange color",
    "small wooden spoon with curved handle and round bowl white shiny smooth long and thin",
    "blue mermaid with scales made",
    "antique ivory curved harp strings",
    "matte gray military military dagger",
    "thick gold bracelet with large square green gemstone in center",
    "metal drill with black handle and blue tip",
    "soldier holding rifle standing",
    "pastel pink silk-draped chaise lounge",
    "mystical purple amulet with symbols",
    "leather-bound ornate crossbow with flintlock",
    "silver necklace with red zircon",
    "golden locket with intricate pattern",
    "futuristic plasma gun with energy core",
    "ornate brass candle holder with flickering flame",
    "small wooden hammer with screws",
    "orange metal pliers with long handles",
    # "sapphire-studded sharp spear",
    # "emerald pendant", 
    # "bottle of red wine with cork in it",
    # "crystal staff with swirling light",
    # "harp adorned with pearl inlays and gilded frame",
    # "necklace with heart-shaped pendant made of silver and turquoise stones",
    # "bottle of red wine with cork in it",
    # "cupcake with chocolate icing on top", 
    # "matte black candle holder two interlocking pieces",
    # "greek kylix cup black-figure technique mythological scenes",
    # "small round blue creature with long nose and pointed ears",
    # "tall glass of layered lemonade",
    # "cylindrical glass of bubbly lemonade"
    # "example prompt (commented out)",
    "large pink stone on black background",
    "pink alien with tentacles on its head",
    "gold chain with infinity symbol and cross pendant",
    "white bolt with hexagonal shape",
    "small pink robot with round eyes and metal arms",
    "aquamarine hairpin with spiral form",
    "ivory maiden with lute",
    "white van cargo boxes subarban",
    "green hexagonal torso on robot",
    "organge plastic cup with two handles on either side of cup",
    "yellow robot with shiny metallic surface",
    "pink frosted donus hold on stick",
    "short green creature with long tail and sharp claws",
    "diamond suspended by platinum chain"
] 